[project]
name = "v2raya-avtomatic"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.16"
dependencies = [
    "aiohttp>=3.12.15",
    "loguru>=0.7.3",
    "pydantic-settings>=2.10.1",
    "requests>=2.32.4",
]
